quarkus:
  http:
    port: 8081
"%dev":
  kafka:
    bootstrap:
      servers: kafka:9092
  mp:
    messaging:
      incoming:
        time-in:
          topic: time
          value:
            deserializer: org.apache.kafka.common.serialization.StringDeserializer
          key:
            deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto:
            offset:
              reset: latest
            group:
              id: ${quarkus.uuid}
          batch:
            max-size: 32
  org:
    eclipse:
      store:
        rest:
          enabled: true
"%test":
  quarkus:
    kafka:
      devservices:
        enabled: false
