quarkus:
  http:
    port: 8081
  datasource:
    db-kind: postgresql
    username: postgres
"%dev":
  kafka:
    bootstrap:
      servers: kafka:9092
  mp:
    messaging:
      incoming:
        time-in:
          topic: time
          value:
            deserializer: com.example.consumer.CustomDeserializer
          key:
            deserializer: org.apache.kafka.common.serialization.StringDeserializer
          auto:
            offset:
              reset: latest
            group:
              id: ${quarkus.uuid}
          batch:
            max-size: 10
  quarkus:
    datasource:
      password: example
      jdbc:
        url: jdbc:postgresql://localhost:5432/
    hibernate-orm:
      database:
        generation: drop-and-create
"%test":
  quarkus:
    kafka:
      devservices:
        enabled: false
